CREATE TABLE IF NOT EXISTS user(username varchar(50) not null primary key,password varchar(50) not null,question varchar(50) not null,answer varchar(50) not null);
CREATE TABLE IF NOT EXISTS payment (adate date NOT NULL,rs int(11) NOT NULL,remark text NOT NULL,type text NOT NULL)
CREATE TABLE IF NOT EXISTS clients (id integer PRIMARY KEY AUTO_INCREMENT,name text NOT NULL,address text NOT NULL,mobile int(12) NOT NULL,phone int(12) NOT NULL)
CREATE TABLE IF NOT EXISTS expenses( id integer PRIMARY KEY AUTO_INCREMENT,adate date NOT NULL, name text NOT NULL,rs double NOT NULL)
CREATE TABLE IF NOT EXISTS ot( adate date NOT NULL, name text NOT NULL,hour int(2) NOT NULL)
CREATE TABLE IF NOT EXISTS labour_payment (adate date NOT NULL,name text NOT NULL,rs decimal(10,0) NOT NULL,ot decimal(10,0) NOT NULL,total decimal(10,0) NOT NULL,shift int(1) NOT NULL)
CREATE TABLE IF NOT EXISTS labour_attendance (name text NOT NULL,Jun text NOT NULL)
CREATE TABLE IF NOT EXISTS labour_details (id integer PRIMARY KEY AUTO_INCREMENT,name text NOT NULL,other text NOT NULL)
CREATE TABLE IF NOT EXISTS production (adate date NOT NULL,tf int(11) NOT NULL,fh int(11) NOT NULL,ts int(11) NOT NULL)
CREATE TABLE IF NOT EXISTS production_payas (adate date NOT NULL,tf int(11) NOT NULL,fh int(11) NOT NULL,ts int(11) NOT NULL)
CREATE TABLE IF NOT EXISTS production_oras (adate date NOT NULL,tf int(11) NOT NULL,fh int(11) NOT NULL,ts int(11) NOT NULL)
CREATE TABLE IF NOT EXISTS production_34gram (adate date NOT NULL,tf int(11) NOT NULL,fh int(11) NOT NULL,ts int(11) NOT NULL)
CREATE TABLE IF NOT EXISTS raw_material (id integer PRIMARY KEY AUTO_INCREMENT,adate date NOT NULL,raw text NOT NULL,type text NOT NULL,quantity int(11) NOT NULL)
CREATE TABLE IF NOT EXISTS raw_material_payas (id integer PRIMARY KEY AUTO_INCREMENT,adate date NOT NULL,raw text NOT NULL,type text NOT NULL,quantity int(11) NOT NULL)
CREATE TABLE IF NOT EXISTS raw_material_oras (id integer PRIMARY KEY AUTO_INCREMENT,adate date NOT NULL,raw text NOT NULL,type text NOT NULL,quantity int(11) NOT NULL)
CREATE TABLE IF NOT EXISTS raw_material_34gram (id integer PRIMARY KEY AUTO_INCREMENT,adate date NOT NULL,raw text NOT NULL,type text NOT NULL,quantity int(11) NOT NULL)
CREATE TABLE IF NOT EXISTS sell ( id integer PRIMARY KEY AUTO_INCREMENT,adate date NOT NULL,client text NOT NULL,item text NOT NULL,quantity int(11) NOT NULL,rate double NOT NULL,total double NOT NULL,paid text NOT NULL)
CREATE TABLE IF NOT EXISTS stock_maintenance(tf int(11) NOT NULL,fh int(11) NOT NULL,ts int(11) NOT NULL, preform250 int(11) NOT NULL,preform500 int(11) NOT NULL,preform1000 int(11) NOT NULL,lable250 int(11) NOT NULL,lable500 int(11) NOT NULL,lable1000 int(11) NOT NULL,caps250 int(11) NOT NULL,caps500 int(11) NOT NULL,caps1000 int(11) NOT NULL,boxes250 int(11) NOT NULL,boxes500 int(11) NOT NULL,boxes1000 int(11) NOT NULL)
CREATE TABLE IF NOT EXISTS stock_maintenance_payas(tf int(11) NOT NULL,fh int(11) NOT NULL,ts int(11) NOT NULL, preform250 int(11) NOT NULL,preform500 int(11) NOT NULL,preform1000 int(11) NOT NULL,lable250 int(11) NOT NULL,lable500 int(11) NOT NULL,lable1000 int(11) NOT NULL,caps250 int(11) NOT NULL,caps500 int(11) NOT NULL,caps1000 int(11) NOT NULL,boxes250 int(11) NOT NULL,boxes500 int(11) NOT NULL,boxes1000 int(11) NOT NULL)
CREATE TABLE IF NOT EXISTS stock_maintenance_oras(tf int(11) NOT NULL,fh int(11) NOT NULL,ts int(11) NOT NULL, preform250 int(11) NOT NULL,preform500 int(11) NOT NULL,preform1000 int(11) NOT NULL,lable250 int(11) NOT NULL,lable500 int(11) NOT NULL,lable1000 int(11) NOT NULL,caps250 int(11) NOT NULL,caps500 int(11) NOT NULL,caps1000 int(11) NOT NULL,boxes250 int(11) NOT NULL,boxes500 int(11) NOT NULL,boxes1000 int(11) NOT NULL)
CREATE TABLE IF NOT EXISTS stock_maintenance_34gram(tf int(11) NOT NULL,fh int(11) NOT NULL,ts int(11) NOT NULL, preform250 int(11) NOT NULL,preform500 int(11) NOT NULL,preform1000 int(11) NOT NULL,lable250 int(11) NOT NULL,lable500 int(11) NOT NULL,lable1000 int(11) NOT NULL,caps250 int(11) NOT NULL,caps500 int(11) NOT NULL,caps1000 int(11) NOT NULL,boxes250 int(11) NOT NULL,boxes500 int(11) NOT NULL,boxes1000 int(11) NOT NULL)

